version: "3.9"
services:
  frontend:
    image: sahil/frontend-app:latest
    ports:
      - "8000:80"
    networks:
      - app-net

  backend:
    image: sahil/backend-app:latest
    ports:
      - "9000:9000"
    networks:
      - app-net

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app-net

networks:
  app-net:

volumes:
  dbdata: