version: '3.8'

services:
  frontend:
    build: ./FRONTEND
    ports:
      - "8000:80"
    depends_on:
      - backend
    networks:
      - testing_default

  backend:
    build: ./BACKEND
    ports:
      - "9000:9000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=mydb
      - DB_USER=user
      - DB_PASSWORD=pass
    networks:
      - testing_default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=mydb
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - testing_default

networks:
  testing_default:
    driver: bridge