apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  postgres-user: dXNlcg== # base64-encoded "user"
  postgres-password: cGFzcw== # base64-encoded "pass"
  postgres-db: bXlkYg== # base64-encoded "mydb"